### ISSUE TITLE
Create component that will fill the mugs with suspicious and less suspicious liquids of different planetary origins

### ISSUE THREAD

**Issue by Nantiopa** [Nantiopa/xmundo#4]
Tasks:
1. Create a scheme to visualise component (objects, their attributes, functions ie) 
2. Cooperate with AI to get functioning code in JavaScript
3. Brainstorm to shape the component further 

--- @Nantiopa ----
Have in mind, that all changes related to this feature should be done in separate branch (feature/mug) recommended. 
-- @dfurmans added ---

**Comment by Nantiopa** [comment]
@dfurmans I will draw the scheme in Canva so I can keep its different versions as we progress with this design. I have sent you an invitation so you can have edit access to the scheme. Peek is available[ here](https://www.canva.com/design/DAGKLIplvIA/3895gVbQ-Z8ZR-nVL3zz2Q/view?utm_content=DAGKLIplvIA&utm_campaign=designshare&utm_medium=link&utm_source=editor) .

**Comment by dfurmans** [comment]
Yeah! All great ! Let's do it so

**Comment by dfurmans** [comment]
Sylwia, Please create in other branch all stuff that will be related to this topic. Thanks ☀️

**Comment by Nantiopa** [comment]
Ok, I have created a new branch divided from main instead of develop, so we do not have index.html with code for photo carousel  there anymore.
